#Выбираем api версию для работы с сервисами в kubernetes
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
#Выбираем с какими подами будем работать, настраиваем порты и тип сервиса
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
