image: gumidu/php-app-gurenich:latest

replicaCount: 6

#resources:
 # requests:
  #  memory: "128Mi"
   # cpu: "100m"
#  limits:
 #   memory: "256Mi"
  #  cpu: "200m"

#service:
 # name: php-service
  #type: LoadBalancer
 # port: 80
  #targetPort: 80
